version: '2'
services:

  web-client:
    image: node:9.3.0-alpine
    working_dir: /home/web-client
    command: yarn start
    volumes:
      - ./web-client:/home/web-client
      - ./web-client/node_modules:/home/web-client/node_modules:delegated
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=$NODE_ENV

  thermometer-sensor:
    image: node:9.3.0-alpine
    working_dir: /home/thermometer-sensor
    command: yarn start
    volumes:
      - ./thermometer-sensor:/home/thermometer-sensor
      - ./thermometer-sensor/node_modules:/home/thermometer-sensor/node_modules:delegated
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$SERVER_PORT
