version: '2'
services:

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  thermometer-sensor:
    image: node:9.3.0-alpine
    working_dir: /home/thermometer-sensor
    command: yarn start
    volumes:
      - ./thermometer-sensor:/home/thermometer-sensor
    depends_on:
      - redis
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$SENSOR_SERVER_PORT
      - NCHAN_URL=$NCHAN_URL
      - SENSOR_REDIS_URL=$SENSOR_REDIS_URL

  notification:
    image: meroje/alpine-nchan:latest
    working_dir: /home/notification
    volumes:
      - ./notification:/home/notification
    ports:
      - 9090:80
    volumes:
      - ./notification/nginx.conf:/etc/nginx/nginx.conf

  data-ingestion:
    image: node:9.3.0-alpine
    working_dir: /home/data-ingestion
    command: yarn start
    volumes:
      - ./data-ingestion:/home/data-ingestion
    depends_on:
      - thermometer-sensor
    environment:
      - NODE_ENV=$NODE_ENV
      - SENSOR_URL=$SENSOR_URL

  integration-tests:
    image: node:9.3.0-alpine
    working_dir: /home/integration-tests
    depends_on:
      - thermometer-sensor
      - notification
    volumes:
      - ./integration-tests:/home/integration-tests
    environment:
      - NODE_ENV=$NODE_ENV
      - NCHAN_URL=$NCHAN_URL
      - SENSOR_URL=$SENSOR_URL
      - SENSOR_REDIS_URL=$SENSOR_REDIS_URL
